# Generated by Django 3.2 on 2023-12-04 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
    ]
