# Generated by Django 3.2 on 2023-12-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20231210_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticias.categoria'),
            preserve_default=False,
        ),
    ]
